language: go
os:
- linux
go:
- 1.10.1
sudo: required
script:
- go get -t ./...
- go generate
- go test ./...
- go get github.com/karalabe/xgo
- |
  # Get the full go repo url
  REPO=$(pwd |  rev | cut -d'/' -f-3 | rev)

  # Get the name of the app
  APP="${PWD##*/}"

  # Get this tag as the version
  VERSION=$(git describe --abbrev=0 --tags)

  # Ensure a fresh build folder
  rm -rf build && mkdir build
  # Compile
  xgo \
    -dest build/ \
    -buildmode=plugin  \
    --targets=darwin/amd64,freebsd/386,freebsd/amd64,freebsd/arm,linux/386,linux/amd64,linux/arm64  \
    --ldflags "-X plugin.version=${VERSION}" \
    $REPO

  # Package
  cd build
  # For each compiled binary, we're repackaging it in a zip with the architecture name, and
  # renaming the binary to the app name
  for FILE in $(ls .); do
    mv $FILE $APP.so
    tar cvzf ${FILE}.tgz $APP.so
    rm -f $APP.so
  done
  cd ..

deploy:
  provider: releases
  api_key:
    secure: Zmrp/FxMYZu37z4uMiOIHnVxS7GXYf9lE3mb+IEeMK+LkX9JW8s2w4mGo32KbsSx/ZjliFciHEU0N8sd+O8O6sNAPRpzSpD1C1Izw13r8fEMvcozl2ZiuC/I/6xseFE9QAoMXxdzSG95YPtcKqOyXCA4j45/T3f3XHnfczFXqQYSgacyWqSRWk6wbCBZPLIhDpjptBQ21qP/yJ62FI1m3833KRuhd1hh1d4vwW9dwD0jYi5JLAI9X29p3/tZzszPCpV9acFUKDVVCoobbW3HOyxNy7T9zb5eZWiNvqjW3qbZ3DzwHJcD19YfV36soLAHeMZocCiP2TxgibdR2IuM+SsuYdE6hhZ5MVGPZpTNppifyPTW47Y+gZPoSdi366yz93PvuhGpTZFUhcLchg+vLczBFt8SPi1AzFghELZGCN8KeyyfqZLpv+2qUJ1RM7yzD7FMRZ6kAuOS6Degb3bj0RDB3onjbgjTc7JIqYNRVkmlY/KtWI9PpBMxhl4FPPVrFvPbaSDiBqJ9kNtPDT/f8repmtisq9Cob5PtW/kFODTzWilqJrX1mZYXt8ERMaI6LsnPTweqQjaaTQ0pHS049wmeBgaLSL3UC8UKcZ08Wp7wQsn1m1ecZU6+VmWr++gwonZc6AC1UQwmId+B8pg6MOkDoqE6jskV6u7rDrNC+kk=
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true